# Generated by Django 5.2.2 on 2025-11-24 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaturauniversitaria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carrerauniversitaria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudianteuniversitario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registroacademicouniversitario',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='estudianteuniversitario',
            name='prototipo_e_codigo__4c7519_idx',
        ),
        migrations.RemoveIndex(
            model_name='estudianteuniversitario',
            name='prototipo_e_carrera_b72e6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='estudianteuniversitario',
            name='prototipo_e_anio_in_4cef71_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroacademicouniversitario',
            name='prototipo_r_estudia_e59ae6_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroacademicouniversitario',
            name='prototipo_r_asignat_699072_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroacademicouniversitario',
            name='prototipo_r_rendimi_b6bc0a_idx',
        ),
        migrations.RemoveField(
            model_name='asignaturauniversitaria',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='asignaturauniversitaria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='asignaturauniversitaria',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='carrerauniversitaria',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='carrerauniversitaria',
            name='coordinador',
        ),
        migrations.RemoveField(
            model_name='estudianteuniversitario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='estudianteuniversitario',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='creditos_actividades_extracurriculares_adicional',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='creditos_ajuste_reconocimientos_adicional',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_total_por_metodo',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='creditos_asignaturas_regulares',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='creditos_practicas_empresa_adicional',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='creditos_total_adicional',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='datos_lms_mensuales',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='dias_acceso_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='dias_acceso_recursos_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='eventos_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='eventos_recursos_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='examenes_enviados_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='fecha_extraccion_datos',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='minutos_totales_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='rendimiento_academico_anio_previo_1',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='rendimiento_academico_anio_previo_2',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='rendimiento_academico_anio_previo_3',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='rendimiento_academico_semestre_1',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='rendimiento_academico_semestre_2',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='rendimiento_academico_total_anio',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='tareas_entregadas_lms',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='registroacademicouniversitario',
            name='visitas_lms',
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='detalle_mensual_lms',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='dias_recursos_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='dias_wifi_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='eventos_lms_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='eventos_recursos_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='examenes_enviados_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='rendimiento_anio_previo_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='rendimiento_anio_previo_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='rendimiento_anio_previo_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='rendimiento_semestre_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='rendimiento_semestre_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='rendimiento_total_anio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='tareas_entregadas_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='tiempo_total_minutos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registroacademicouniversitario',
            name='visitas_lms_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignaturauniversitaria',
            name='anio_carrera',
            field=models.IntegerField(help_text='Año del plan de estudios (1-6)'),
        ),
        migrations.AlterField(
            model_name='asignaturauniversitaria',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.carrerauniversitaria'),
        ),
        migrations.AlterField(
            model_name='asignaturauniversitaria',
            name='codigo_asignatura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asignaturauniversitaria',
            name='creditos',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='asignaturauniversitaria',
            name='nombre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='carrerauniversitaria',
            name='campus',
            field=models.CharField(help_text='Ubicación: Valencia, Gandía, Alcoy', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrerauniversitaria',
            name='codigo_carrera',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carrerauniversitaria',
            name='creditos_totales_requeridos',
            field=models.DecimalField(decimal_places=2, default=240.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='carrerauniversitaria',
            name='nombre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='anio_ingreso_universidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='anio_inicio_estudios',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='prototipo.carrerauniversitaria'),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='cerca_de_finalizacion_carrera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='codigo_estudiante',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='dedicacion_estudios',
            field=models.CharField(choices=[('TiempoCompleto', 'Tiempo Completo'), ('TiempoParcial', 'Tiempo Parcial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='es_desplazado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='es_plan_antiguo_adaptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='es_segunda_titulacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='estado_abandono',
            field=models.CharField(help_text='Variable Objetivo: Abandono vs NoAbandono', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='nivel_educativo_madre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='nivel_educativo_padre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='nota_selectividad_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='nota_selectividad_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='orden_preferencia_carrera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='tiene_impagos_matricula',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudianteuniversitario',
            name='tipo_acceso_universidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='anio_academico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='anio_carrera_maximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='anio_carrera_minimo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.asignaturauniversitaria'),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_actividades_extracurriculares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_ajuste_reconocimientos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anio_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anio_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anio_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anio_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anio_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anio_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_anuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_especiales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_examen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_semestre_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_semestre_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_titulo_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_aprobados_total_anio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anio_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anio_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anio_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anio_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anio_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anio_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_anuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_movilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_oficiales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_practicas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_semestre_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_semestre_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_matriculados_total_anio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_pendientes_acta_oficial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_pendientes_titulo_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='creditos_practicas_empresa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.estudianteuniversitario'),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='id_grupo_creditos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='matricula_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registroacademicouniversitario',
            name='nota_final_asignatura',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
