# Generated by Django 5.2.2 on 2025-12-04 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0002_alter_asignaturauniversitaria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSeguimientoEstudiante',
            fields=[
                ('estudiante', models.OneToOneField(help_text='Estudiante al que pertenece esta ficha', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_seguimiento', serialize=False, to='prototipo.estudianteuniversitario')),
                ('en_seguimiento', models.BooleanField(default=False, help_text='True si el estudiante está en seguimiento activo')),
                ('fecha_inicio_seguimiento', models.DateField(blank=True, help_text='Fecha en que comenzó el seguimiento', null=True)),
                ('ultimo_indice_riesgo', models.FloatField(blank=True, help_text='Último índice de riesgo calculado', null=True)),
                ('ultima_clasificacion', models.CharField(blank=True, choices=[('bajo', 'Riesgo Bajo'), ('medio', 'Riesgo Medio'), ('alto', 'Riesgo Alto'), ('critico', 'Riesgo Crítico')], help_text='Última clasificación de riesgo', max_length=10, null=True)),
                ('fecha_ultima_prediccion', models.DateTimeField(blank=True, help_text='Fecha de la última predicción', null=True)),
                ('total_alertas', models.IntegerField(default=0, help_text='Total de alertas generadas')),
                ('alertas_activas', models.IntegerField(default=0, help_text='Alertas pendientes o en revisión')),
                ('total_intervenciones', models.IntegerField(default=0, help_text='Total de intervenciones realizadas')),
                ('intervenciones_exitosas', models.IntegerField(default=0, help_text='Intervenciones con resultado exitoso')),
                ('notas_generales', models.TextField(blank=True, help_text='Notas generales sobre el seguimiento del estudiante')),
                ('ultima_fecha_contacto', models.DateField(blank=True, help_text='Última vez que se contactó al estudiante', null=True)),
                ('proxima_fecha_contacto', models.DateField(blank=True, help_text='Próxima fecha programada de contacto', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se creó la ficha')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización de la ficha')),
                ('tutor_principal', models.ForeignKey(blank=True, help_text='Tutor principal asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_tutorados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Seguimiento',
                'verbose_name_plural': 'Fichas de Seguimiento',
                'db_table': 'ficha_seguimiento_estudiante',
            },
        ),
        migrations.CreateModel(
            name='PrediccionDesercion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se generó la predicción')),
                ('probabilidad_desercion', models.FloatField(help_text='Probabilidad de deserción (0.0 a 1.0)')),
                ('indice_riesgo', models.FloatField(db_index=True, help_text='Índice de riesgo calculado (0 a 100)')),
                ('clasificacion_riesgo', models.CharField(choices=[('bajo', 'Riesgo Bajo'), ('medio', 'Riesgo Medio'), ('alto', 'Riesgo Alto'), ('critico', 'Riesgo Crítico')], db_index=True, help_text='Clasificación del nivel de riesgo', max_length=10)),
                ('factores_riesgo', models.JSONField(blank=True, default=list, help_text='Lista de factores que contribuyen al riesgo')),
                ('importancia_factores', models.JSONField(blank=True, default=dict, help_text='Importancia de cada factor (SHAP values)')),
                ('modelo_usado', models.CharField(default='XGBoost', help_text='Algoritmo ML utilizado', max_length=100)),
                ('version_modelo', models.CharField(default='1.0', help_text='Versión del modelo ML', max_length=50)),
                ('accuracy_modelo', models.FloatField(blank=True, help_text='Precisión del modelo al momento de predicción', null=True)),
                ('es_cambio_significativo', models.BooleanField(default=False, help_text='True si hubo cambio importante vs predicción anterior')),
                ('cambio_clasificacion', models.CharField(blank=True, help_text='Descripción del cambio de clasificación', max_length=50)),
                ('activa', models.BooleanField(default=True, help_text='True si es la predicción más reciente')),
                ('estudiante', models.ForeignKey(help_text='Estudiante al que pertenece esta predicción', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prototipo.estudianteuniversitario')),
            ],
            options={
                'verbose_name': 'Predicción de Deserción',
                'verbose_name_plural': 'Predicciones de Deserción',
                'db_table': 'prediccion_desercion',
                'ordering': ['-fecha_prediccion'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('cambio_riesgo', 'Cambio de Clasificación'), ('riesgo_alto', 'Riesgo Alto Detectado'), ('inactividad', 'Inactividad Prolongada'), ('bajo_rendimiento', 'Bajo Rendimiento Académico'), ('ausentismo', 'Ausentismo Elevado'), ('manual', 'Alerta Manual')], help_text='Tipo de alerta', max_length=20)),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], db_index=True, default='media', help_text='Nivel de prioridad', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], db_index=True, default='pendiente', help_text='Estado actual de la alerta', max_length=15)),
                ('titulo', models.CharField(help_text='Título descriptivo de la alerta', max_length=200)),
                ('mensaje', models.TextField(help_text='Descripción detallada de la alerta')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se creó la alerta')),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Momento en que se empezó a revisar', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Momento en que se resolvió', null=True)),
                ('acciones_tomadas', models.TextField(blank=True, help_text='Descripción de las acciones realizadas')),
                ('notificacion_enviada', models.BooleanField(default=False, help_text='True si se envió notificación por email')),
                ('fecha_notificacion', models.DateTimeField(blank=True, help_text='Momento en que se envió la notificación', null=True)),
                ('email_destinatarios', models.JSONField(blank=True, default=list, help_text='Lista de emails que recibieron notificación')),
                ('visible', models.BooleanField(default=True, help_text='True si la alerta debe mostrarse')),
                ('estudiante', models.ForeignKey(help_text='Estudiante que generó la alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='prototipo.estudianteuniversitario')),
                ('tutor_asignado', models.ForeignKey(blank=True, help_text='Tutor responsable de atender la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('prediccion', models.ForeignKey(blank=True, help_text='Predicción que originó la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='prototipo.predicciondesercion')),
            ],
            options={
                'verbose_name': 'Alerta de Estudiante',
                'verbose_name_plural': 'Alertas de Estudiantes',
                'db_table': 'alerta_estudiante',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='IntervencionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intervencion', models.CharField(choices=[('tutoria', 'Tutoría Académica'), ('psicologica', 'Apoyo Psicológico'), ('vocacional', 'Orientación Vocacional'), ('financiera', 'Asesoría Financiera'), ('seguimiento', 'Seguimiento General'), ('reunion', 'Reunión con Estudiante'), ('contacto_familia', 'Contacto con Familia'), ('derivacion', 'Derivación a Especialista'), ('otro', 'Otro')], help_text='Tipo de intervención realizada', max_length=20)),
                ('fecha_intervencion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la intervención')),
                ('titulo', models.CharField(help_text='Título o resumen de la intervención', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la intervención')),
                ('resultado', models.CharField(choices=[('exitosa', 'Exitosa'), ('parcial', 'Parcialmente Exitosa'), ('sin_efecto', 'Sin Efecto'), ('pendiente', 'Pendiente de Evaluar')], default='pendiente', help_text='Resultado de la intervención', max_length=15)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales o seguimiento')),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='True si requiere intervención de seguimiento')),
                ('fecha_seguimiento', models.DateField(blank=True, help_text='Fecha programada para seguimiento', null=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Documento o archivo relacionado', null=True, upload_to='intervenciones/%Y/%m/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Momento en que se registró en el sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('alerta_relacionada', models.ForeignKey(blank=True, help_text='Alerta que motivó esta intervención', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='prototipo.alertaestudiante')),
                ('estudiante', models.ForeignKey(help_text='Estudiante que recibió la intervención', on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='prototipo.estudianteuniversitario')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario que realizó o registró la intervención', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervención de Estudiante',
                'verbose_name_plural': 'Intervenciones de Estudiantes',
                'db_table': 'intervencion_estudiante',
                'ordering': ['-fecha_intervencion'],
                'indexes': [models.Index(fields=['estudiante', '-fecha_intervencion'], name='intervencio_estudia_20ad2b_idx'), models.Index(fields=['tipo_intervencion', '-fecha_intervencion'], name='intervencio_tipo_in_3fa006_idx'), models.Index(fields=['-fecha_intervencion'], name='intervencio_fecha_i_a246a6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='predicciondesercion',
            index=models.Index(fields=['estudiante', '-fecha_prediccion'], name='prediccion__estudia_7f043c_idx'),
        ),
        migrations.AddIndex(
            model_name='predicciondesercion',
            index=models.Index(fields=['clasificacion_riesgo', '-indice_riesgo'], name='prediccion__clasifi_9124cb_idx'),
        ),
        migrations.AddIndex(
            model_name='predicciondesercion',
            index=models.Index(fields=['-fecha_prediccion'], name='prediccion__fecha_p_557024_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestudiante',
            index=models.Index(fields=['estado', 'prioridad', '-fecha_creacion'], name='alerta_estu_estado_dcf936_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestudiante',
            index=models.Index(fields=['estudiante', '-fecha_creacion'], name='alerta_estu_estudia_024f24_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestudiante',
            index=models.Index(fields=['-fecha_creacion'], name='alerta_estu_fecha_c_763224_idx'),
        ),
    ]
