# Generated by Django 5.2.2 on 2025-12-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0003_fichaseguimientoestudiante_predicciondesercion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrediccionDesercion',
            new_name='TrazabilidadPrediccionDesercion',
        ),
    ]
