# Generated by Django 5.2.2 on 2025-12-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0004_rename_predicciondesercion_trazabilidadpredicciondesercion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador General'), ('coordinador_carrera', 'Coordinador de Carrera'), ('analista', 'Analista')], default='analista', max_length=30)),
                ('carrera_asignada', models.ForeignKey(blank=True, help_text='Solo para coordinadores de carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prototipo.carrerauniversitaria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
